# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'intersol-test' do
pod 'AFNetworking', '~> 2.5'
pod 'TestFlightSDK', '~> 3.0'
pod 'Vkontakte-iOS-SDK-LV'
pod 'GameCenterManager', '~> 5.3'
end

target 'intersol-testTests' do

end

